### ISSUE TITLE
Unintentional override

### ISSUE THREAD

**Issue by v411e** [mooncoffee1/MyHyprBackup#1]
See these lines:

https://github.com/mooncoffee1/MyHyprBackup/blob/7f4e65925be6f82d5e6df766058b29c2380df78c/.config/hypr/hyprland.conf#L167

https://github.com/mooncoffee1/MyHyprBackup/blob/7f4e65925be6f82d5e6df766058b29c2380df78c/.config/hypr/hyprland.conf#L170

**Comment by mooncoffee1** [comment]
ah ye, ur right, fixing rn, Thx!
